substitutions:
  device: security-panel
  name: Security Panel
  reboot_timeout: 2h
  update_interval: 5min
  log_level: INFO
  static_address: ${device}.local

esphome:
  name: ${device}
  platform: ESP32
  board: esp-wrover-kit

packages:
  common_no_wifi: !include common/common_no_wifi.yaml
  wt32_eth01: !include common/wt32_eth01.yaml

binary_sensor:

# Front Door
  - platform: gpio
    pin:
      number: 15
      mode:
        input: true
        pullup: true
    name: "Front Door"
    device_class: door

# Back Door
  - platform: gpio
    pin:
      number: 14
      mode:
        input: true
        pullup: true
    name: "Back Door"
    device_class: door
    filters:
      - delayed_on: 100ms

# Garage Entry Door
  - platform: gpio
    pin:
      number: 12
      mode:
        input: true
        pullup: true
    name: "Garage Entry Door"
    device_class: door

# Front Hall Motion
  - platform: gpio
    pin:
      number: 2
      mode:
        input: true
        pullup: true
    name: "Front Hall Motion"
    device_class: motion

# Smoke Alarm
  - platform: gpio
    pin:
      number: 4
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Smoke Alarm"
    device_class: smoke

# Sump Overflow
  - platform: gpio
    pin:
      number: 32
      mode:
        input: true
        pullup: true
    name: "Sump Overflow"
    device_class: moisture

# Tamper Detection
  - platform: gpio
    pin:
      number: 33
      mode:
        input: true
        pullup: true
    name: "Tamper Detection"
    device_class: tamper

switch:

# Siren
  - platform: gpio
    pin:
      number: 17
    name: "Siren"
    restore_mode: ALWAYS_OFF
