######################################
# 
######################################

substitutions:
  device: smart-plug-sa102-7
  name: Smart Plug SA102_7
  static_address: ${device}.local
  zoozee_switch_icon: "mdi:power"
  reboot_timeout: 1d
  update_interval: 5min
  write_state_to_flash: "true"
  log_level: INFO
  
packages: 
  zoozee: !include common/zoozee.yaml
