esphome:
  name: ${device}
  platform: ESP8266
  board: esp01_1m
  esp8266_restore_from_flash: ${write_state_to_flash}

packages:
  common: !include common.yaml

# Toggle Button
binary_sensor:
  - platform: gpio
    pin: GPIO13 #GPIO13
    id: button
    on_press:
      then:
        - switch.toggle: relay

# Power Relay
switch:
  - platform: gpio
    pin: GPIO15 #GPIO15
    name: ${name}
    icon: ${wion_switch_icon}
    id: relay
    
# Blue LED
status_led:
  pin:
    number: GPIO2
    inverted: true
